bec-project/bec

bec_lib/pyproject.toml

While the bec server already has the dependency, using just bec_lib would crash on import as the dotenv module would not be available

fix: add missing dotenv dependency

---

bec_server/tests/tests_scan_server/test_procedures.py

- makes sure the client is shutdown after procedure tests
- note that this should be handled by the procedure worker for any external process workers in the future, but not for the in-process worker which is tested here, since that would shut down the client for the process in the real BEC instance

fix(test): dangling client thread

---

bec_server/bec_server/device_server/__init__.py
bec_server/bec_server/device_server/cli/launch.py
bec_server/tests/tests_device_server/test_device_server.py
bec_server/tests/tests_device_server/test_device_server_cli_launch.py

The encoding must be set before any other ophyd or pyepics import. To this end, this PR removes the (unnecessary) imports of the device server module to ensure that the launch.py file can properly set the encoding according to the plugin config.
closes #491

[BUG]: fix encoding for temperature pvs

---

bec_lib/bec_lib/bec_service.py
bec_server/bec_server/device_server/devices/device_serializer.py
bec_server/tests/tests_device_server/test_device_serializer.py

This MR allows the device server to deal with lazy signals for device serialization, i.e. not try to connect to signals with `wait_for_connection()` if `.hints` is called. See issue #457 for more details. In addition, it improves logging of the Redis Host for bec_services to avoid a service being stuck due to not being able to connect to Redis because of a missconfiguration
closes #457 
closes #476

Allow device server to deal with lazy signals

---

bec_lib/bec_lib/device.py
bec_lib/bec_lib/devicemanager.py
bec_lib/bec_lib/endpoints.py
bec_lib/bec_lib/tests/test_config.yaml
bec_lib/bec_lib/tests/utils.py
bec_lib/tests/test_device_manager.py
bec_server/bec_server/device_server/bec_message_handler.py
bec_server/bec_server/device_server/devices/device_serializer.py
bec_server/bec_server/device_server/devices/devicemanager.py
bec_server/pyproject.toml
bec_server/tests/tests_device_server/test_device_manager_ds.py

This PR adds a default subscription to the BEC signals. These signals will fully replace the custom bec events at some point but for now, they co-exist until we've migrated all repositories. To better separate the core events from the about to be deprecated bec-specific events, this PR also separates the subscription into dedicated methods. 
`_subscribe_to_bec_device_events` can be removed once we've fully migrated to BEC signals. 
closes #441

subscribe to BEC signals

---

bec_lib/bec_lib/atlas_models.py
bec_lib/bec_lib/device.py
bec_lib/bec_lib/devicemanager.py
bec_lib/tests/test_devices.py
bec_server/tests/tests_scihub/test_atlas_config_handler.py

- make `DeviceBase` run the config initialisation through a relaxed model to ensure all required keys are present
- update tests to match
- tidy tests a little

refactor: enforce device config keys

---

bec_lib/bec_lib/endpoints.py
bec_lib/bec_lib/messages.py
bec_server/bec_server/scihub/atlas/atlas_connector.py
bec_server/tests/tests_scihub/test_atlas_connector.py

This PR adds endpoint info to redis. This is useful for clients written in a different language to inspect the available endpoints and their signature. 
closes #323

feat(endpoints): publish endpoint info to redis; closes #323

---

bec_lib/bec_lib/config_helper.py
bec_server/bec_server/scihub/atlas/config_handler.py

- Split `send_config_request` into two parts to control waiting for the response, for use in BEC Widgets to deactivate the GUI while waiting
- Expose a list of non-updatable config keys

refactor: expose more config handler function

---

bec_lib/bec_lib/bec_service.py
bec_lib/bec_lib/logger.py
bec_lib/tests/test_bec_service.py
bec_server/bec_server/device_server/bec_message_handler.py
bec_server/tests/tests_device_server/test_device_manager_ds.py

This is just a quick fix to add the scan id to the progress message. Once we've migrated everything to use the bec signal, we can elevate the scan id to a proper pydantic field (cf #521). 
It also adds a fix for the initialization of the logger tests (introduced with #518).

fix(progress_signal): progress message must include scan id

---

bec_server/bec_server/device_server/devices/config_update_handler.py

handle the case when a config update has `None` for `deviceConfig`, which is allowed by the model in `bec_lib/bec_lib/atlas_models.py`

fix: handle none dictionary in config update

---

bec_lib/bec_lib/bec_service.py
bec_server/bec_server/device_server/devices/device_serializer.py

The PR fixes a bug and improves the error message if a bec_service is not unique: 
- 1. The method `get_lazy_wait_for_connection(obj)` needs PVs to be connected. This PR ensures that
- 2. If a bec_service is already running, it raises the Runtime Error with proper message directly now

fix: bug in device serialization

---

.github/actions/bec_e2e_install/action.yml
.github/actions/bec_install/action.yml
.github/actions/plugin_repo_tests/action.yml
.github/workflows/child_repos.yml
.github/workflows/ci.yml
.github/workflows/end2end.yml

This PR adds a child pipeline improves the CI pipeline for BEC.
It adds:
- child pipeline for ophyd_devices
- child pipelines for plugin repositories (allowed to fail)
- moves e2e test into independent action. Can be reused by other repositories 
Note, which tests should be mandatory to pass for BEC. At the moment, child_repos are allowed to fail. Should this remain like this?
PS: Even with GITLAB Token, gitlab.psi.ch sometimes rejects the cloning of the plugin repository.

Add child pipeline for ophyd_devices

---

bec_server/bec_server/bec_server_utils/launch.py
bec_server/bec_server/bec_server_utils/service_handler.py
bec_server/bec_server/bec_server_utils/tmux_launch.py

On systems with systemd, a shared tmux socket is used to allow privileged users that have access to the server to connect to the running tmux session, launched with a service account

feat(bec-server cli): add support for shared tmux socket; enable systemd

---

bec_ipython_client/bec_ipython_client/callbacks/live_table.py
bec_ipython_client/tests/client_tests/test_live_table.py

EPICS may report negative precisions to indicate a different formatting. This PR adds support to switch accordingly and also fixes the (valid) precision of 0.

feat(ipython): add support for negative precisions in epics

---

bec_ipython_client/tests/end-2-end/test_scans_lib_e2e.py
bin/bec_set_account/go.mod
bin/bec_set_account/go.sum
bin/bec_set_account/main.go

This PR adds a CLI tool to change the account endpoint within redis. For the deployments, this should be used to change the account endpoint in redis. The compiled script is bec-set-account and can be called via:
``` {bash}
./bec-set-account --help
Usage of ./bec-set-account:
-pgroup string
Process group (e.g. p16602 )
-redis-host string
Redis host (e.g. awi-bec-001)
./bec-set-account -pgroup p10101 -redis-host localhost
```
Please note:
When an account change is requested, user input is needed to confirm the change. The default response is N, however, this can be changed if needed.
For beamlines, an additional wrapper should exist that sets the redis-host based on deployments, i.e. 'production'(should be default) or 'test'. and also limits the access to allow only specific groups to …

Add go script for account management CLI

---

.github/workflows/ci.yml
.github/workflows/end2end.yml
bec_ipython_client/tests/end-2-end/test_scans_lib_e2e.py
bec_lib/bec_lib/file_utils.py
bec_lib/bec_lib/service_config.py
bec_lib/tests/test_bec_logger.py
bec_lib/tests/test_bec_service.py
bec_lib/tests/test_file_utils.py
bec_server/bec_server/scan_server/scan_worker.py
bec_server/tests/tests_scan_server/test_scan_worker.py

This PR fixes the hardcoded 'data' and 'logs' structure for file and log writing. Instead, we will now directly use the basepath as specified in the config. Relies on https://git.psi.ch/psd_deployments/roles/psi.bec/-/merge_requests/4 to be merged together for the deployments.

Fix basepath for filewriter logs

---

bec_lib/bec_lib/scan_history.py
bec_lib/tests/test_scan_history.py

The scan history needs to be filtered to readable items, otherwise the GUI accessing the scan history will raise immediately after changing accounts. 
closes #548

fix(scan history): filter scan history to readable files

---

.github/workflows/semantic_release.yml
bec_server/bec_server/scan_server/procedures/Containerfile.requirements
bec_server/bec_server/scan_server/procedures/Containerfile.worker

Add a step following the release to build an image containing a python env with the requirements for bec, and push it to ghcr
(I know there's a CI commit tag, but I would like there to be a release made with merging this)

feat(ci): build and push requirements image

---

bec_ipython_client/bec_ipython_client/callbacks/live_table.py
bec_ipython_client/tests/client_tests/test_live_table.py

A check in the live table allowed exiting the live updates if the live data has no entries and the scan is closed. However, it falsely claimed that this was due to missing monitored devices without actually checking. 
Fast scans, such as a simple acquire, could therefore finish before ever receiving the first scan segment and thus warn the user about a wrongly configured device configuration. 
This PR fixes the issue by actively checking the readout priority.

fix(live table): fix check for monitored devices

---

bec_server/bec_server/device_server/cli/launch.py
bec_server/bec_server/device_server/devices/device_serializer.py
bec_server/bec_server/device_server/devices/devicemanager.py
bec_server/tests/tests_device_server/test_device_manager_ds.py
bec_server/tests/tests_device_server/test_device_serializer.py

This PR improves 2 things:
(A)
It introduces a change for log message that will intercept any loggings from the 'ophyd' package and forwards them to the bec_logger. This will help identifying issues directly linked to ophyd where exceptions are not always properly attached to status objects, but only logged. One example for this is a failed move due to an alarm state (https://github.com/bluesky/ophyd/blob/main/ophyd/epics_motor.py#L304).
(B)
It fixes handling of the device serialization. Thereby, it checks that all signal_names are unique which is linked to issue #564. In addition, in case the device serialization fails for `connect=True` and `connect=False`, we now forward the proper error message

Improve DeviceServer device handling and logging

---

bec_lib/bec_lib/messages.py
bec_lib/bec_lib/script_executor.py
bec_lib/tests/test_script_executor.py

This PR includes minor improvements to the script executor:
* Add default ttl for scripts. Previously, scripts were automatically cleaned up after execution but for development it is better to clean up after some time. 
* Add traceback info to `ScriptExecutionInfoMessage`. This will allows us to send error messages to the IDE. The traceback frames are trimmed to the actual execution. 
* Add "aborted" exit status and fix KeyboardInterrupt handling

feat(script executor): improve message interface for aborted scripts

---

bec_server/bec_server/file_writer/file_writer.py
bec_server/tests/tests_file_writer/test_file_writer.py

This PR fixes a bug that made the FileWriter crash it's writing process in case a file_path in the file_references did not exist. 
closes #608

Bugfix for non-existing filepath in file_ref

---

bec_server/bec_server/scan_server/scans.py

The fermat's spiral was missing the optim trajectory as movement parameter of the GUI config

fix(fermat_scan): add optim_trajectory to movement parameters

---

bec_lib/bec_lib/atlas_models.py

specifying the default_factory is mutually exclusive to the default field. The make_all_fields_optional utility function did not respect it though. This PR fixes it.

Fix make_all_fields_optional

---

bec_lib/bec_lib/scan_history.py
bec_lib/tests/test_scan_history.py

This PR fixes the signature and return value for the history access by scan numbers. Scan number are not unique and therefore may return a list of scan containers instead of just a single item.

fix(history): allow list of scans by scan number

---

bec_ipython_client/tests/end-2-end/test_scans_lib_e2e.py
bec_lib/bec_lib/device.py
bec_lib/tests/test_devices.py
docs/source/user/command_line_interface.md

Now that read operations can bypass the queue, we can set the default to cached=False. 
https://github.com/bec-project/bec_widgets/pull/869 needs to be merged first

fix(device): update default cached behavior for read methods to False
